<?php include $config['VIEW_PATH'] . 'headers' . DS . 'header.phtml'?>


<div class="container">
        <div class="table-wrapper pt-5">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2>Products <b>List</b></h2></div>
                    <div class="col-sm-4">
                        <a class="btn btn-outline-primary  mx-5" href="?page=createList" >New listing</a>
                    </div>
                </div>
            </div>
            <table class="table table-hover  table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Description</th>
                        <th>Categorie</th>
                        <th>Image</th>
                    </tr>
                </thead>
                <tbody>
                    
                    <?php 
                        if(!$listingEmpty){
                            foreach($listingResult as $item){
                                echo '<tr>';
                                echo '  <td>' . $item['prodName'] . '</td>';
                                echo '  <td>' . filterPrice($item['prodPrice']) . ' $ </td>';
                                echo '  <td>' . $item['prodDescription'] . '</td>';
                                echo '  <td>' . categorieName($item['categorie']) . '</td>';
                                echo '  <td><img src="' .  fileWithExt($item['pic']) . '" height="50" width="100"></td>';
                                echo '  <td><a href="?page=modifyItem&itemId=' . $item['prodId'] . '&itemPic=' .  $item['pic'] . '" class= "btn btn-info" >modify</a></td>';
                                echo '  <td><a href="?page=listings&del=' . $item['prodId'] . '" class ="btn btn-danger">delete</a></td>';   
                                
                                echo '</tr>';
                            }
                         }
                    ?>
                    
                </tbody>
            </table>
        </div>
    </div>  













<?php include $config['VIEW_PATH'] . 'footers' . DS . 'footer.phtml'?>