<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
    body { background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);}
    .error-template {padding: 40px 15px;text-align: center;}
    .error-actions {margin-top:15px;margin-bottom:15px;}
    .error-actions .btn { margin-right:10px; }

</style>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                   Site policie</h1>
                
                <div class="error-details">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras risus mauris, consectetur id facilisis ut, tristique in nisl. Nulla sit amet tortor sit amet diam auctor congue quis sed eros. Nunc accumsan viverra nunc eget maximus. Suspendisse congue lorem in aliquet aliquet. Maecenas placerat sapien velit, ac rutrum urna accumsan quis. Cras porttitor hendrerit erat vitae posuere. Nunc at arcu ullamcorper mi laoreet ullamcorper. Curabitur turpis turpis, pulvinar eu egestas a, viverra at neque. Maecenas suscipit luctus aliquam. Cras leo ipsum, rutrum sed semper a, faucibus in nisl. Morbi suscipit diam sed placerat rutrum. Mauris tristique scelerisque velit, eleifend consequat turpis rutrum et.

Nullam luctus facilisis cursus. Praesent tempor porttitor dolor, tincidunt aliquam felis convallis molestie. Aliquam porta tristique lacus, quis ullamcorper justo sollicitudin quis. Donec ut commodo felis. Aenean maximus luctus sodales. Vivamus blandit non dui eu condimentum. Pellentesque a dignissim nibh, sed lacinia nisi. Pellentesque eget nulla ex. Curabitur in est maximus, sagittis lacus tincidunt, bibendum sapien. Curabitur ut accumsan nunc. Quisque fringilla risus id mauris sodales, vel accumsan lorem vulputate. Praesent tempor porttitor turpis, id pharetra metus accumsan sed. Fusce bibendum justo sed eros eleifend, vitae sollicitudin ligula blandit. Nunc eu mi id est mattis tempor at quis mauris.

Sed varius auctor ornare. Curabitur dictum tincidunt nibh et tincidunt. Suspendisse lacinia augue lectus, sit amet cursus magna posuere ac. Donec interdum posuere risus, ac rhoncus orci molestie non. Pellentesque vitae tristique nisl, quis placerat nisl. Etiam in ipsum metus. Vestibulum ut fermentum libero, dapibus commodo sapien.

Proin quis viverra urna. Integer ut augue ex. In sed arcu ipsum. Donec dignissim dui vel neque commodo varius. Pellentesque tristique quam sem, in molestie diam porta egestas. Nam laoreet venenatis sem, non iaculis justo laoreet ac. Donec iaculis tempus elementum. Etiam fermentum lectus id nisi malesuada, et ultrices libero lobortis. Vestibulum hendrerit, nunc non congue accumsan, metus mi egestas magna, sodales pulvinar velit nisi sit amet justo.

Integer a est nibh. Etiam metus quam, molestie id erat eu, fermentum condimentum nunc. Nulla lectus sem, malesuada nec ante ut, venenatis malesuada velit. Maecenas finibus fringilla augue, a suscipit odio. Duis molestie euismod enim ut faucibus. Sed lacinia justo ut magna viverra, eu suscipit libero varius. Vivamus ullamcorper malesuada velit sed viverra. Vivamus commodo felis vitae rutrum tincidunt. Suspendisse velit nisi, varius quis sapien ac, ultrices bibendum purus. Morbi vel nisi eget mauris posuere pellentesque.
                </div>
                <div class="error-actions">
                    <a href="?page=signup" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                        Back </a>
                        
                </div>
            </div>
        </div>
    </div>
</div>
